# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create([
  {username: "Eris", email: "eris@discordia.net", password: "golden_apple"},
  {username: "Marlene", email: "eight_of_hearts@bridgeclub.com", password: "shuffleboard"},
  {username: "UserThree", email: "UserThree@trollmail.com", password:"DROP DATABASE *;"},
  {username: "p1c@$$0", email: "thethe_perception@gmail.com", password:"gl17ch_@r7"},
  {username: "Whirlybro", email: "chad_a_mcmasters@princeton.edu", password: "ROFLCOPTER"},
  {username: "Pete", email: "pete@hotmail.com", password: "t22versyn!"},
  {username: "AcelaX", email: "choo-choo@amtrak-fans.net", password: "superliner++"},
  {username: "NEETzche", email: "no_god@gmail.com", password: "nihil_supernum"},
  {username: "tina", email: "tina@gmail.com", password: "password"},
  {username: "Wizard", email: "The_GM@tabletop.com", password: "rocksfall"}
])

servers = Server.create([
  {owner_id: users[0].id, name: "test"},
  {owner_id: users[0].id, name: "Home"},
  {owner_id: users[2].id, name: "SQL Fun :)"},
  {owner_id: users[7].id, name: "Atheist General"},
  {owner_id: users[4].id, name: "EXPLOSIONS :kappa:"},
  {owner_id: users[5].id, name: "IRC"},
  {owner_id: users[6].id, name: "Trains"},
  {owner_id: users[3].id, name: "Gl17ch @r7 @ppr3c1@71on"},
  {owner_id: users[1].id, name: "Bridge Chat"},
  {owner_id: users[2].id, name: "--DROP TABLES * FROM servers;"},
  {owner_id: users[4].id, name: "Exam SADS!!!1"},
  {owner_id: users[3].id, name: "Ar71s7 C0rn3r"},
  {owner_id: users[9].id, name: "Serious Roleplay"},
  {owner_id: users[4].id, name: "Linux Chat"},
  {owner_id: users[1].id, name: "I don't understand technology"},
  {owner_id: users[1].id, name: "Oh darn"}
])

memberships = Membership.create([
  {user_id: users[0].id, server_id: servers[0].id},
  {user_id: users[0].id, server_id: servers[1].id},
  {user_id: users[0].id, server_id: servers[2].id},
  {user_id: users[0].id, server_id: servers[3].id},
  {user_id: users[0].id, server_id: servers[4].id},
  {user_id: users[0].id, server_id: servers[5].id},
  {user_id: users[0].id, server_id: servers[6].id},
  {user_id: users[0].id, server_id: servers[7].id},
  {user_id: users[0].id, server_id: servers[8].id},
  {user_id: users[0].id, server_id: servers[9].id},
  {user_id: users[0].id, server_id: servers[10].id},
  {user_id: users[0].id, server_id: servers[11].id},
  {user_id: users[0].id, server_id: servers[12].id},
  {user_id: users[0].id, server_id: servers[13].id},
  {user_id: users[0].id, server_id: servers[14].id},
  {user_id: users[0].id, server_id: servers[15].id},
  {user_id: users[1].id, server_id: servers[15].id},
  {user_id: users[1].id, server_id: servers[14].id},
  {user_id: users[1].id, server_id: servers[8].id},
  {user_id: users[1].id, server_id: servers[1].id},
  {user_id: users[1].id, server_id: servers[5].id},
  {user_id: users[2].id, server_id: servers[0].id},
  {user_id: users[2].id, server_id: servers[1].id},
  {user_id: users[2].id, server_id: servers[2].id},
  {user_id: users[2].id, server_id: servers[5].id},
  {user_id: users[2].id, server_id: servers[9].id},
  {user_id: users[2].id, server_id: servers[13].id},
  {user_id: users[3].id, server_id: servers[1].id},
  {user_id: users[3].id, server_id: servers[3].id},
  {user_id: users[3].id, server_id: servers[7].id},
  {user_id: users[3].id, server_id: servers[11].id},
  {user_id: users[4].id, server_id: servers[1].id},
  {user_id: users[4].id, server_id: servers[2].id},
  {user_id: users[4].id, server_id: servers[4].id},
  {user_id: users[4].id, server_id: servers[6].id},
  {user_id: users[4].id, server_id: servers[10].id},
  {user_id: users[4].id, server_id: servers[14].id},
  {user_id: users[5].id, server_id: servers[1].id},
  {user_id: users[5].id, server_id: servers[3].id},
  {user_id: users[5].id, server_id: servers[5].id},
  {user_id: users[5].id, server_id: servers[12].id},
  {user_id: users[5].id, server_id: servers[13].id},
  {user_id: users[6].id, server_id: servers[6].id},
  {user_id: users[6].id, server_id: servers[1].id},
  {user_id: users[6].id, server_id: servers[12].id},
  {user_id: users[7].id, server_id: servers[3].id},
  {user_id: users[7].id, server_id: servers[4].id},
  {user_id: users[7].id, server_id: servers[7].id},
  {user_id: users[7].id, server_id: servers[11].id},
  {user_id: users[7].id, server_id: servers[13].id},
  {user_id: users[8].id, server_id: servers[1].id},
  {user_id: users[8].id, server_id: servers[9].id},
  {user_id: users[9].id, server_id: servers[1].id},
  {user_id: users[9].id, server_id: servers[12].id},
  {user_id: users[9].id, server_id: servers[5].id},
  {user_id: users[9].id, server_id: servers[6].id},
  {user_id: users[2].id, server_id: servers[14].id},
  {user_id: users[2].id, server_id: servers[4].id}
])


invites = Invite.create([
  {server_id: servers[0].id, num_uses: 3},
  {server_id: servers[0].id, num_uses: 2},
  {server_id: servers[0].id, num_uses: 1},
  {server_id: servers[1].id, num_uses: 10000},
  {server_id: servers[1].id, num_uses: 2},
  {server_id: servers[1].id, num_uses: 1},
  {server_id: servers[2].id, num_uses: 3},
  {server_id: servers[2].id, num_uses: 2},
  {server_id: servers[2].id, num_uses: 1},
  {server_id: servers[3].id, num_uses: 3},
  {server_id: servers[3].id, num_uses: 2},
  {server_id: servers[3].id, num_uses: 1},
  {server_id: servers[4].id, num_uses: 3},
  {server_id: servers[4].id, num_uses: 2},
  {server_id: servers[4].id, num_uses: 1},
  {server_id: servers[5].id, num_uses: 3},
  {server_id: servers[5].id, num_uses: 2},
  {server_id: servers[5].id, num_uses: 1},
  {server_id: servers[6].id, num_uses: 3},
  {server_id: servers[6].id, num_uses: 2},
  {server_id: servers[6].id, num_uses: 1},
  {server_id: servers[7].id, num_uses: 3},
  {server_id: servers[7].id, num_uses: 2},
  {server_id: servers[7].id, num_uses: 1},
  {server_id: servers[8].id, num_uses: 3},
  {server_id: servers[8].id, num_uses: 2},
  {server_id: servers[8].id, num_uses: 1},
  {server_id: servers[9].id, num_uses: 3},
  {server_id: servers[9].id, num_uses: 2},
  {server_id: servers[9].id, num_uses: 1},
  {server_id: servers[10].id, num_uses: 3},
  {server_id: servers[10].id, num_uses: 2},
  {server_id: servers[10].id, num_uses: 1},
  {server_id: servers[11].id, num_uses: 3},
  {server_id: servers[11].id, num_uses: 2},
  {server_id: servers[11].id, num_uses: 1},
  {server_id: servers[12].id, num_uses: 3},
  {server_id: servers[12].id, num_uses: 2},
  {server_id: servers[12].id, num_uses: 1},
  {server_id: servers[13].id, num_uses: 3},
  {server_id: servers[13].id, num_uses: 2},
  {server_id: servers[13].id, num_uses: 1},
  {server_id: servers[14].id, num_uses: 3},
  {server_id: servers[14].id, num_uses: 2},
  {server_id: servers[14].id, num_uses: 1},
  {server_id: servers[15].id, num_uses: 3},
  {server_id: servers[15].id, num_uses: 2},
  {server_id: servers[15].id, num_uses: 1}
])

channels = Channel.create([
  {server_id: servers[0].id, name: "test_channel"},
  {server_id: servers[0].id, name: "test_test"},
  {server_id: servers[0].id, name: "testy"},
  {server_id: servers[1].id, name: "General"},
  {server_id: servers[1].id, name: "Introductions"},
  {server_id: servers[1].id, name: "Server Shilling"},
  {server_id: servers[2].id, name: "--SELECT *"},
  {server_id: servers[2].id, name: "FROM users"},
  {server_id: servers[2].id, name: "WHERE passwords"},
  {server_id: servers[3].id, name: "General"},
  {server_id: servers[3].id, name: "Jokes (just like religion)"},
  {server_id: servers[3].id, name: "Dawkins Appreciation"},
  {server_id: servers[4].id, name: "General"},
  {server_id: servers[4].id, name: "BOOOOSH (images)"},
  {server_id: servers[4].id, name: "KABOOM (text)"},
  {server_id: servers[5].id, name: "General"},
  {server_id: servers[5].id, name: "freenode"},
  {server_id: servers[5].id, name: "espernet"},
  {server_id: servers[6].id, name: "General"},
  {server_id: servers[6].id, name: "Amtrak"},
  {server_id: servers[6].id, name: "International"},
  {server_id: servers[7].id, name: "G3n3r@l"},
  {server_id: servers[7].id, name: "01d $k001"},
  {server_id: servers[7].id, name: "N3w @g3"},
  {server_id: servers[8].id, name: "General"},
  {server_id: servers[8].id, name: "Strategy :)"},
  {server_id: servers[8].id, name: "Play Bridge!"},
  {server_id: servers[9].id, name: "--DROP DATABASE"},
  {server_id: servers[9].id, name: "*"},
  {server_id: servers[9].id, name: ";--"},
  {server_id: servers[11].id, name: "G3n3r@l"},
  {server_id: servers[11].id, name: "@r71$7s"},
  {server_id: servers[11].id, name: "@ppr3c1@70rz"},
  {server_id: servers[10].id, name: "General"},
  {server_id: servers[10].id, name: "Study club :("},
  {server_id: servers[10].id, name: "Fun and explosions!"},
  {server_id: servers[12].id, name: "General"},
  {server_id: servers[12].id, name: "Looking For Group"},
  {server_id: servers[12].id, name: "Roleplay Corner (IC only)"},
  {server_id: servers[13].id, name: "General"},
  {server_id: servers[13].id, name: "Troubleshooting"},
  {server_id: servers[13].id, name: "Programming"},
  {server_id: servers[14].id, name: "General"},
  {server_id: servers[14].id, name: "How does this thing work again?"},
  {server_id: servers[14].id, name: "Oh gosh sorry I thought this was Help"},
  {server_id: servers[15].id, name: "General"},
  {server_id: servers[15].id, name: "Dagnabbit"},
  {server_id: servers[15].id, name: "How do I work this?"},
  {server_id: servers[0].id, name: "Another test"},
  {server_id: servers[0].id, name: "Banlist"},
  {server_id: servers[2].id, name: "--SELECT"},
  {server_id: servers[2].id, name: "* FROM invites"},
  {server_id: servers[4].id, name: "BOOOOOM (videos)"},
  {server_id: servers[5].id, name: "Channel Ideas"},
  {server_id: servers[6].id, name: "Specs"},
  {server_id: servers[10].id, name: "Problem Sets :("},
  {server_id: servers[11].id, name: "C0mm1$$10n$"},
  {server_id: servers[12].id, name: "Arcadia (IC only - Arcadia setting)"},
  {server_id: servers[1].id, name: "Reports"},
  {server_id: servers[0].id, name: "Moderator Discussion"},
  {server_id: servers[0].id, name: "Test Hidden Channels"},
  {server_id: servers[0].id, name: "Test Edit Permissions"}
])